spring:
  cloud:
    nacos:
      discovery:
        namespace: dubbo
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    enabled: true
    path: /v3/api-docs
  group-configs:
    - group: Platform
      paths-to-match: "/**"
      packages-to-scan: io.github.liruohrh.apiplatform.controller
knife4j:
  enable: true
  setting:
    language: zh_cn
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
