spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/api_platform?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: root
    password: 123456
  redis:
#   如果有redisson配置，则redisson不读redis配置
    redisson:
      file: classpath:/redisson.yml
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group:  Platform
      paths-to-match: '/**'
      packages-to-scan: io.github.liruohrh.apiplatform.controller
knife4j:
  enable: true
  setting:
    language: zh_cn
logging:
  level:
    io.github.liruohrh.apiplatform.exception: warn
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl