spring:
  config:
    import:
      - file:./private/mail.yml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: api-platform
  profiles:
    active: dev
  mail:
    #username
    #password
    default-encoding: utf-8
    host: smtp.163.com
    properties:
      mail:
        smtp:
          ssl:
            enable: true
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        enabled: true
        register-enabled: true
        service: ${spring.application.name}
        ip-type: IPv4
        namespace: e0673429-263b-49f1-9a4f-ea0527d5b07b
        group: ${spring.profiles.active}
server:
  port: 8080
  servlet:
    context-path: /api-platform
dubbo:
  application:
    name: api-platform
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos
    address: nacos://localhost:8848?namespace=e0673429-263b-49f1-9a4f-ea0527d5b07b
    group: dubbo-${spring.profiles.active}
    register-mode: instance
api-platform:
  login:
    white-list:
      - /doc.html
      - /webjars/**
      - /favicon.ico
      - /swagger-ui.html
      - /v3/api-docs/**
      - /email/captcha
      - /oss/file
      - /user/login
      - /user/register
      - /user/passwd
      - /oss/static/**