springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group:  Platform
      paths-to-match: '/**'
      packages-to-scan: io.github.liruohrh.apiplatform.controller
knife4j:
  enable: true
  setting:
    language: zh_cn